Portfolio - mobile menu
SimonGideon/My-Portfolio- pull request #24
Opened 2022-10-10 23:31 UTC by SimonGideon

In this PR I:

1. Use basic JavaScript syntax.
2. Use JavaScript to manipulate DOM elements.
3. Use JavaScript events.

2022-10-10 23:43 UTC, topeogunleye reviewed
Hi @SimonGideon, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that uses JavaScript without ESLint setup. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-10 23:59 UTC, codecaiine requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Project works as expected :heavy_check_mark: 
- No linters errors :heavy_check_mark: 
- Good commits history :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-10 23:59 UTC, codecaiine commented on index.html
> +      </div>
- [ ] Good job so far your mobile menu works as expected :clap: However there are some issues with your design :cry: Please make sure that your menu option underline is smaller like the one on the Figma template. Please make ensure you that your menu Xmark and menu option have the same size, color, and position as defined on the Figma template...   because as a developer it is important to pay attention to details and stick to the chosen template as much as possible :smile:

![Screenshot from 2022-10-10 23-55-45](https://user-images.githubusercontent.com/6615394/194969507-7e073f46-ef5f-40d5-a26b-5098a7f82c3c.jpg)

2022-10-11 04:56 UTC, rloterh commented on index.html
> +      </div>
well resolved! ✔️

2022-10-11 05:04 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Simon,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾Congratulations!  🎉💯🌟 

## Highlights 👍
- Nice job for using cursor pointer for the mobile menu
- Mobile menu is working as intended

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

_Kindly consider my comments marked **[OPTIONAL]** under this review_

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

**You can also consider:**
- MIT license link in your ReadMe is broken, kindly endeavor to fix it.
Implementing the above change(s) will make your ReadMe standout even better.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-11 05:04 UTC, rloterh commented on index.html
> +      </div>
- [ ] OPTIONAL
Kindly ensure that your menu items have enough spacing in-between them, as can be seen in the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)

**Your mobile menu:**
![image](https://user-images.githubusercontent.com/12745474/195000992-847d8693-5fbf-44f1-95e9-13d3dea7ecb1.png)


**Figma mobile menu:**
![image](https://user-images.githubusercontent.com/12745474/195001061-0d19a501-54da-4de3-9947-239a62a5e4ac.png)

2022-10-11 05:20 UTC, merged