Portfolio: desktop version
SimonGideon/My-Portfolio- pull request #4
Opened 2022-09-28 16:22 UTC by SimonGideon

In this PR, I:
1. Uses media queries in your CSS file to make your desktop version look like the template you selected (Desktop: 768px or wider).
2. Used Grid and Flexbox to layout components on the page.
3. Flexible elements on the page.
4. Fixed the font sizing using view width (vw)

2022-09-28 16:56 UTC, aimalamiri requested changes
Hi @SimonGideon, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191347504-9f70659c-a01f-48a1-ad46-b8722d46ffca.gif)

## Highlights

- The desktop version is designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 16:56 UTC, aimalamiri commented on Index.html
> -                </ul>
Good job! This looks very nice, but you can follow the Figma template to improve the design by removing the extra space between the elements.

![image](https://user-images.githubusercontent.com/34779928/192841982-697d9083-0a6e-4fc4-85b5-5548a56f3a83.png)

2022-09-28 16:56 UTC, aimalamiri commented on Index.html
> +        <div class="card">
As you see in the Figma template, the image for the even cards is on the right, and the image for the odd cards is on the left. 

**Tip: You can use the `nth-child()` function in here. Look at [this](https://www.w3schools.com/cssref/sel_nth-child.asp)**

![image](https://user-images.githubusercontent.com/34779928/192842830-cedd5d1f-b064-46d6-b476-37b3e31a663b.png)

2022-09-28 21:14 UTC, SimonGideon commented on Index.html
> +        <div class="card">
@aimalamiri Hello, I have implemented the nth-child and now I can access the odd and even children.
```
  /* reverse the nth child of project */
  .work div:nth-child(even) {
    display: none;
  }
```
Under Class work,  I have 3 projects similar to project-1 given below. My question is how can I access the image div inside and swap their order?
```
<section class="work">
      <!-- project-1 -->
      <div class="project-1 projects">
        <div class="card">
          <div>
            <img src="/images/project_1.svg" alt="project_1"/>
          </div>
          <div>
            <span><h2>Tonic</h2></span>
            <div class="compn-lan">
              <p>CANOPY</p>
              <ul>
                <li>Back End Dev</li>
                <li>2015</li>
              </ul>
            </div>
            <div class="card-body">
              <p>
                A daily selection of privately personalized reads; no accounts
                or sign-ups required.
              </p>
            </div>
            <div class="technology">
              <ul>
                <li>html</li>
                <li>css</li>
                <li>javaScript</li>
              </ul>
            </div>
            <button class="button">See Project</button>
          </div>
        </div>
      </div>
</section>
```

2022-09-28 21:53 UTC, SimonGideon commented on Index.html
> +        <div class="card">
## 🎉 :clinking_glasses: After a long struggle made it out of the rubbit hole. :smiley: 
![giphy](https://user-images.githubusercontent.com/61404403/192895173-66804473-a276-4ed9-90a7-653a954181b3.gif)

2022-09-28 22:38 UTC, Alfredbis29 requested changes
Hi @SimonGideon ,
 
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

 ## Highlights
- Good readMe :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- No linter errors :heavy_check_mark: 

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
-N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 22:38 UTC, Alfredbis29 commented on css/styles.css
> +  /* work-section */
- [ ] Good work on making some changes so far, but you still need to enhance your design for your project to look fantastic, but you're almost there. Please minimize the gap between your work sections to make your project looks like one for Figma design. :wink: 

This is how your work section look like :point_down: 
![spacebetweensections](https://user-images.githubusercontent.com/88894525/192899566-66236d0b-6ebf-43de-84f6-51244339b1a3.png)

Figma Design :point_down: 
![figmaworksection](https://user-images.githubusercontent.com/88894525/192899829-d550b05f-8901-458b-ad34-af9c9eb6b7c6.png)

2022-09-28 22:38 UTC, Alfredbis29 requested changes
Hi @SimonGideon ,
 
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

 ## Highlights
- Good readMe :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- No linter errors :heavy_check_mark: 

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
-N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 23:14 UTC, SimonGideon commented
@Alfredbis29 Applied the suggested changes to the Section requested by the previous reviewer.

2022-09-29 03:45 UTC, mgmediaweb approved these changes
Hi @SimonGideon , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approved5](https://user-images.githubuserco💯 t.com/41912912/192933799-dbd953a7-1d3c-4e54-b4f0-49b5809d5283.gif)

## Highlights :100
- Good job following the advice of the previous reviewer ✔️ 

## Optional suggestions

[OPTIONAL] Kindly, I suggest you use "A" tags for the main menu (navbar)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 04:21 UTC, merged